### ISSUE TITLE
Magento EE 1.9

### ISSUE THREAD

**Issue by Khaleel** [webcomm/magento-boilerplate#129]
Hey

Thanks for making this an opensource theme. My question does this work on Magento EE (1.14.1.0 ) and also Magento 1.9.x ??

**Comment by WebBen** [comment]
I use it on Mage 1.9.x and soo far works everything fine.

**Comment by ollyboy** [comment]
Hey I'm on 1.9.1.1 and the top nav has gone missing. I have other themes as stores and top nav is fine for them. Is it something to do with JR_CleverCMs. Have an AWS box up at moment on http://ec2-54-153-192-78.ap-southeast-2.compute.amazonaws.com/ with admin steve steve33

**Comment by bencorlett** [comment]
Hi there,

JR CleverCms? Magento Boilerplate isn’t using this module, certainly hasn’t since pre-v1 :)

**Comment by ollyboy** [comment]
Ok I was using the https://github.com/mercator/mercator stack which has an older version. I changed composer to get your version and now I get:

2015-07-17T06:55:50+00:00 ERR (3): 
Mage_Core_Exception: message 'Invalid block type: Webcomm_BootstrapNavigation_Block_Page_Html_Topmenu', code '0' in /var/www/mercator/app/Mage.php:595
#0 /var/www/mercator/app/code/core/Mage/Core/Model/Layout.php(495): Mage->throwException('Invalid block type: Webcomm_BootstrapNavigation_Block_Page_Html_Topmenu')
#1 /var/www/mercator/app/code/core/Mage/Core/Model/Layout.php(437): Mage_Core_Model_Layout->_getBlockInstance('page/html_topmenu', Array)
#2 /var/www/mercator/app/code/core/Mage/Core/Model/Layout.php(472): Mage_Core_Model_Layout->createBlock('page/html_topmenu', 'catalog.topnav')
#3 /var/www/mercator/app/code/core/Mage/Core/Model/Layout.php(239): Mage_Core_Model_Layout->addBlock('page/html_topmenu', 'catalog.topnav')
#4 /var/www/mercator/app/code/core/Mage/Core/Model/Layout.php(205): Mage_Core_Model_Layout->_generateBlock(Mage_Core_Model_Layout_Element, Mage_Core_Model_Layout_Element)
#5 /var/www/mercator/app/code/core/Mage/Core/Model/Layout.php(206): Mage_Core_Model_Layout->generateBlocks(Mage_Core_Model_Layout_Element)
#6 /var/www/mercator/app/code/core/Mage/Core/Model/Layout.php(206): Mage_Core_Model_Layout->generateBlocks(Mage_Core_Model_Layout_Element)
#7 /var/www/mercator/app/code/core/Mage/Core/Model/Layout.php(206): Mage_Core_Model_Layout->generateBlocks(Mage_Core_Model_Layout_Element)
#8 /var/www/mercator/app/code/core/Mage/Core/Controller/Varien/Action.php(344): Mage_Core_Model_Layout->generateBlocks()
#9 /var/www/mercator/app/code/core/Mage/Cms/Helper/Page.php(113): Mage_Core_Controller_Varien_Action->generateLayoutBlocks()
#10 /var/www/mercator/app/code/core/Mage/Cms/Helper/Page.php(52): Mage_Cms_Helper_Page->_renderPage(JR_CleverCms_Cms_IndexController, '1')
#11 /var/www/mercator/vendor/mercator/magento-clever-cms/app/code/community/JR/CleverCms/Helper/Cms/Page.php(13): Mage_Cms_Helper_Page->renderPage(JR_CleverCms_Cms_IndexController, '1')
#12 /var/www/mercator/app/code/core/Mage/Cms/controllers/IndexController.php(75): JR_CleverCms_Helper_Cms_Page->renderPage(JR_CleverCms_Cms_IndexController, '1')
#13 /var/www/mercator/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Cms_IndexController->noRouteAction()
#14 /var/www/mercator/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('noRoute')
#15 /var/www/mercator/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Mage_Core_Controller_Request_Http)
#16 /var/www/mercator/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#17 /var/www/mercator/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#18 /var/www/mercator/public/index.php(87): Mage->run('default', 'store')

**Comment by ollyboy** [comment]
Just disabled the JR_CleverCms module and the site came up good!  The mercator stack would not let me do that as it said it was a dependency for magento-boilerplate. I will let the mercator team know. Two things I have learned:
- current mercator stack with latest sample data and patches breaks top nav with this v2dev magento-boilerplate.
- JR_CleverCms and magento-boilerplate v2dev don't like each other

**Comment by aneeshjajodia** [comment]
Will this version of boilerplate work on 1.9.2?

**Comment by bencorlett** [comment]
I haven't undertaken extensive testing but I don't see a reason that it shouldn't :)

Sent from my iPhone

Please excuse my brevity
