### ISSUE TITLE
Gulp error

### ISSUE THREAD

**Issue by azmeehan** [webcomm/magento-boilerplate#76]
Hi, Im pretty green when it comes to Gulp but im having trouble compiling the dependencies for this boilerplate.  As far as im aware everything is installed correctly.
gulp -v
[04:13:03] CLI version 3.8.6
[04:13:03] Local version 3.8.6
bower -v
1.3.8
node -v
v0.10.28
npm -v
1.3.6

The actual error is below and happens when I try to run gulp command from the project directory.

module.js:340
    throw err;
          ^
Error: Cannot find module 'gulp-less'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/public_html/skin/frontend/boilerplate/default/gulpfile.js:28:18)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

Any help is appreciated sorry if this is covered in another thread i searched but couldnt seem to find anything that helped.

**Comment by bencorlett** [comment]
Child themes are something that has been solved in the upcoming version `3.0` of this project. Version 3.0 uses NPM to support the compilation of one or more themes, and uses bower to install the dependencies. Once documentation is completed, I'll release 3.0 and it should really streamline development for you.

**Comment by anthonybachour** [comment]
In case anyone else ran into this problem I solved it by installing libnotify-bin!
